export default {
  amazon: [
    {
      'mainTitle': 'Amazon',
      'platformType': 'amazon',
      'link': './commonOrder.html#/unmatchProduct?platform=amazon',
      'alias': 'unmatchProduct',
      'type': 'Group', // 分组菜单
      'id': 'amazon1'
    }, {
      'mainTitle': '订单检索',
      'platformType': 'amazon',
      'menuKey': 'amazon_orderToRetrieve',
      'link': './commonOrder.html#/orderToRetrieve?platform=amazon',
      'icon': 'icon-sousuowushuju',
      'id': 'amazon9',
      'pid': 'amazon1'
    }, {
      'mainTitle': '异常订单',
      'platformType': 'amazon',
      'menuKey': 'amazon_stockoutOrder',
      'link': './commonOrder.html#/stockoutOrder?platform=amazon',
      'icon': 'iconjinggao',
      'id': 'amazon7',
      'pid': 'amazon1'
    }, {
      'mainTitle': '截留订单',
      'platformType': 'amazon',
      'menuKey': 'amazon_interceptOrder',
      'link': './commonOrder.html#/interceptOrder?platform=amazon',
      'dataItemNum': '0',
      'id': 'amazon5',
      'pid': 'amazon2'
    }, {
      'mainTitle': '标发货',
      'platformType': 'amazon',
      'menuKey': 'amazon_markShipments',
      'link': './commonOrder.html#/markShipments?platform=amazon',
      'icon': 'icon-biaoji',
      'id': 'amazon8',
      'pid': 'amazon1'
    }, {
      'mainTitle': '订单审核',
      'platformType': 'amazon',
      'id': 'amazon2',
      'icon': 'icon-shenhe',
      'type': 'Group-title', // 分组
      'pid': 'amazon1'
    }, {
      'mainTitle': '未匹配商品', // 未匹配商品
      'platformType': 'amazon',
      'menuKey': 'amazon_unmatchProduct',
      'link': './commonOrder.html#/unmatchProduct?platform=amazon',
      'dataItemNum': '0',
      'id': 'amazon3',
      'pid': 'amazon2'
    }, {
      'mainTitle': '可合并',
      'platformType': 'amazon',
      'menuKey': 'amazon_combineOrder',
      'link': './amazon.html#/combineOrder',
      'dataItemNum': '0',
      'id': 'amazon4',
      'pid': 'amazon2'
    }, {
      'mainTitle': '待匹配物流',
      'platformType': 'amazon',
      'id': 'amazon6',
      'icon': 'icon-wuliu1',
      'pid': 'amazon1',
      'dataItemNum': '0',
      'link': './amazon.html#/matchTheLogistics',
      'menuKey': 'amazon_matchTheLogistics'
    }, {
      'mainTitle': 'FBA',
      'platformType': 'amazon',
      'id': 'amazon10',
      'icon': 'icon-shenhe',
      'type': 'Group-title', // 分组
      'pid': 'amazon1'
    }, {
      'mainTitle': 'FBA订单列表',
      'platformType': 'amazon',
      'menuKey': 'amazon_fbaOrder',
      'link': './amazon.html#/fbaOrder?platform=amazon',
      'icon': 'icon-sousuowushuju',
      'id': 'amazon11',
      'pid': 'amazon10'
    }, {
      'mainTitle': '已取消订单', // 已取消订单
      'platformType': 'amazon',
      'menuKey': 'amazon_cancelOrder',
      'link': './amazon.html#/cancelOrder',
      'dataItemNum': '0',
      'icon': 'icon-iconfontzhizuobiaozhun0262',
      'id': 'amazon19',
      'pid': 'amazon1'
    }, {
      'mainTitle': '手工订单',
      'platformType': 'amazon',
      'menuKey': 'amazon_manualOrder',
      'link': './amazon.html#/manualOrder',
      'icon': 'icon-shougong',
      'id': 'amazon16',
      'pid': 'amazon1'
    }, {
      'mainTitle': '导入/导出任务', // 导入导出任务
      'platformType': 'amazon',
      'id': 'amazon18',
      'icon': 'icon-shenhe',
      'type': 'Group-title', // 分组
      'pid': 'amazon1'
    }, {
      'mainTitle': '导入查看',
      'platformType': 'amazon',
      'menuKey': 'amazon_importTask',
      'link': './amazon.html#/importTask',
      'id': 'amazon21',
      'pid': 'amazon18'
    }, {
      'mainTitle': '导出查看',
      'platformType': 'amazon',
      'menuKey': 'amazon_exportTask',
      'link': './amazon.html#/exportTask',
      'id': 'amazon20',
      'pid': 'amazon18'
    }
  ]
};
